# Faye
development:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  auth_token: DEVELOPMENT_SECRET_TOKEN
  adapter: "Faye"
  async: true



# Pusher
# development:
#   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
#   app_id: "YOUR_PUSHER_APP_ID"
#   api_key: "YOUR_PUSHER_API_KEY"
#   auth_token: "YOUR_PUSHER_SECRET"
#   adapter: "Pusher"
#   async: true

# Disabled
# development:
#   adapter: false

test:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "secret"
  async: false

production:
  server: "http://example.com/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "dd55d79c6c06ca8aff9e0c6cc90231ff05d076d5b7db845ed6442e6927395770"
  async: true
